### ISSUE TITLE
"Don't spell like a bugger"

### ISSUE THREAD

**Issue by michaelmior** [invernizzi/Chrisper#10]
I'm going to assume that you're not aware that bugger is a derogatory term. While I assume this was meant to be a joke, many people will not be amused by it and I would suggest changing the message. Furthermore, this assumes that the authors are American (or at least that they desire to use American spelling). This is certainly not always the case so it would be nice if this were configurable.

**Comment by invernizzi** [comment]
Hi Micheal - I apologize, that string comes from a third-party contribution and I had not idea of that meaning. 
You are correct, this is a tool that has been developed in a US research lab.
It wast meant to harmonize the styles of multiple authors with different backgrounds into a consistent writing style.
I'll split your configuration comment into a separate issue - unfortunately though, these days I have almost no time to keep up with my open-source projects: contributions are welcome!

**Comment by michaelmior** [comment]
Totally understandable. Thanks for the reply! I've now moved to an American institution myself, so it's less of a pressing need for me right now :)
